Uitleg over <b>'Ondernemers'</b>

Het invulscherm bestaat uit 3 pagina's:
- Instituut
- Contactpersoon
- URL's

<hr>
In de '<strong>Instituut</strong>' pagina kan men gegevens betreffende het instituut invullen.
Het bestaat uit de volgende velden:
- Volledige instituut naam
- Afkorting
- Bezorgadres straat
- Bezorgadres postcode
- Bezorgadres plaats
- Bezoekadres straat
- Bezoekadres postcode
- Bezoekadres plaats
- Land
- Telefoon
- Fax
- Website
- E-mail
- Jaar van oprichting
- Openingstijden
- Meer informatie

De veldnamen spreken voor zichzelf.
Maar hier toch wat extra informatie.
<strong>Land</strong>veld is een keuzelijst. Indien een land niet in het lijstje staat, dan het het land via het menu'tje helemaal links in het scherm toegevoegd worden. aub. de huidge scherm eerst 'bewaren'!
<strong>E-mail</strong> adres is het adres van het instituut niet van de contactpersoon.
Velden <strong>Openingstijden</strong> en <strong>Meer informatie</strong> zijn vrije teksten waar veel informatie in geplaatst kan worden. Men mag ook html codes gebruiken (liever niet, maar kan).

<hr>
In de '<strong>Contactpersoon</strong>' pagina kan men contactpersoongegevens voor de <strong>huidige</strong> instituut invullen.
Het is mogelijk om per instituut dus meerdere contactpersonen te hebben.
Het invulscherm bestaat uit de volgende velden:
- Functie
- Voornaam
- Tussenvoegsel
- Achternaam
- E-mail
- Telefoon
- Meer informatie

De veldnamen spreken voor zichzelf.

<hr>
In de '<strong>URL's</strong>' pagina kan men per instituut opgeven waar bv. archief en collectie informatie gevonden kan worden.
Het invulscherm bestaat uit de volgende invul velden:
- URL van pagina (waar de betreffende informatie gevonden kan worden)
- Type pagina (wat voor soort informatie betreft het, is het archief informatie, collectie informatie of ..., indien een bepaalde keuze niet in de lijst staat, dan kan een nieuwe keuze toegevoegd worden via het menu helemaal links in het scherm 'URL Types')
- Titel (het kan zijn dat de opgegeven pagina een 'lelijke' titel heeft, indien in dit veld iets wordt ingevuld, dan wordt bij 'ons' altijd deze 'onze' titel gebruikt)

Daarnaast zijn er nog een paar velden die door de computer worden gevuld.
- Laatste update (wanneer is voor het laatst de url ingeladen)
- Status (was het inladen de laatste keer gelukt, Oke - goed, andere meldingen niet goed. Indien niet goed controleer dan de URL dan via Internet Explorer, en pas zondig de URL aan)
- Originele titel (de originele titel die we binnenkrijgen via de url)
- Inhoud zonder html tags (de content van de opgegeven url, maar zonder html codes)

&nbsp;
