<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be 
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision: 5.1 $
   * $Id: themedef.inc,v 5.1 2004/05/31 22:11:12 ivo Exp $
   */

  /** Theme definition */
  $theme["customtpls"] = array("box.tpl");
  $theme["highlight"] = "#ccffcc";
?>
