<?php

	/**
	 * This file is part of the Achievo ATK distribution.
	 * Detailed copyright and licensing information can be found
	 * in the doc/COPYRIGHT and doc/LICENSE files which should be 
	 * included in the distribution.
	 *
	 * @package atk
	 * @subpackage themes
	 *
	 * @copyright (c)2000-2004 Ibuildings.nl BV
	 * @license http://www.achievo.org/atk/licensing ATK Open Source License
	 *
	 * @version $Revision: 5.4 $
	 * $Id: themedef.inc,v 5.4 2004/10/08 20:15:25 sandy Exp $
	 */

	/** Theme definition */
	$theme["customtpls"] = "scan 'templates/'";	
	$theme["customstyles"] = "scan 'styles/'";
	$theme["customimgs"] = array("help.gif","arrowup.gif","arrowdown.gif","dark_back.gif","empty.gif");
	
	$theme["highlight"] = "#c5d7ff";
	$theme["select"]		= "#96a7ff";

	// Outlook menu
//	$theme["ol_menucolor"]="#ffffff";
	$theme["ol_menucolor"]="yellow";
//	$theme["ol_wincolor"]="#eeeee0";
	$theme["ol_wincolor"]="red";
//	$theme["ol_background"]="#677EB1";
	$theme["ol_background"]="#FFFFFF";

	$theme["tabtype"] = "dhtml";
?>
